stages:
  - linting

isort:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - isort . --check-only

black:
  stage: linting
  image:
    name: cytopia/black:latest-py3.8
    entrypoint: ["/bin/ash", "-c"]
  script:
    - python3 -m black --check .
