stages:
  - linting

isort:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - isort . --check-only

black:
  stage: linting
  image: cytopia/black:latest-py3.8
  script:
    - python3 -m black --check -l 120 .

flake8:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - flake8 .

pylint:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - find . -type f -name "*.py" | xargs pylint
