stages:
  - testing
  - linting

isort:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - isort . --check-only

black:
  stage: linting
  image:
    name: cytopia/black:latest-py3.8
    entrypoint: ["/bin/ash", "-c"]
  script:
    - python3 -m black --check .

flake8:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - flake8 .

pylint:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - find . -type f -name "*.py" | xargs pylint

pytest:
  stage: testing
  image: conda/miniconda3
  before_script:
    - conda env create -f environment.yml
    - conda init bash
    - source ~/.bashrc
    - conda activate r2r 
  script:
    - pytest -v