name: robot2robot_transfer
channels:
  - pytorch
  - conda-forge
#  - defaults
dependencies:
  - numpy
  - tqdm
  - pip
  - wandb
  - pybullet
#  - ray-rllib
#  - matplotlib
  - pip:
      - gym
      - "ray[rllib]"
      - klampt