name: r2r
channels:
  - pytorch
  - nvidia
  - conda-forge
#  - defaults
dependencies:
  - numpy
  - tqdm
  - pip
  - wandb
  - pybullet
  - python=3.8
  - pytorch
  - pytorch-cuda
#  - ray-rllib
#  - matplotlib
  - pip:
      - gym
      - "ray[rllib]"
#      - klampt