name: r2r
channels:
  - conda-forge
  - nvidia
  - pytorch
#  - defaults
dependencies:
  - numba
  - numpy
  - pip
  - pybullet
  - pytorch
  - tqdm
  - wandb
  - pip:
      - gym
      - pytorch-lightning
      - "ray[rllib]"
