name: r2r
channels:
  - pytorch
  - nvidia
  - conda-forge
#  - defaults
dependencies:
  - numpy
  - tqdm
  - pip
  - wandb
  - pybullet
  - python=3.8
  - pytorch
  - pytorch-cuda=11.7
  - pip:
      - gym
      - "ray[rllib]"
      - pytorch-lightning